---
k3s_version: v1.24.9+k3s1
# this is the user that has ssh access to these machines
ansible_user: tannerru
systemd_dir: /etc/systemd/system

# Set your timezone
system_timezone: "America/Chicago"

# interface which will be used for flannel
flannel_iface: "eth0"
flannel_cni: "/home/{{ ansible_user }}/10-flannel.conflist"

# apiserver_endpoint is virtual ip-address which will be configured on each master
apiserver_endpoint: "10.0.40.150"

# k3s_token is required  masters can talk together securely
# this token should be alpha numeric only
k3s_token: "pGtwGgV7maWKNGJK9BcCnMeUY"

# The IP on which the node is reachable in the cluster.
# Here, a sensible default is provided, you can still override
# it for each of your hosts, though.
k3s_node_ip: '{{ ansible_facts[flannel_iface]["ipv4"]["address"] }}'

# Disable the taint manually by setting: k3s_master_taint = false
k3s_master_taint: "{{ true if groups['node'] | default([]) | length >= 1 else false }}"

# these arguments are recommended for servers as well as agents:
extra_args: >-
  --node-ip={{ k3s_node_ip }}
  --flannel-iface={{ flannel_iface }}
  --flannel-cni-conf={{ flannel_cni }}

# change these to your liking, the only required are: --disable servicelb, --tls-san {{ apiserver_endpoint }}
extra_server_args: >-
  {{ extra_args }}
  --tls-san {{ apiserver_endpoint }}
  --disable servicelb
  --disable traefik
  {{ '--node-taint node-role.kubernetes.io/master=true:NoSchedule' if k3s_master_taint else '' }}

extra_agent_args: >-
  {{ extra_args }}



#IP/hostname for NAS to use for NFS mounts
truenas: "10.0.50.4"


